# Developed By github.com/@mairhythmhoon 
name: Monthly Log Cleanup

on:
  schedule:
    # 11:30 AM IST
    - cron: "0 6 28-31 * *"

  workflow_dispatch:

jobs:
  cleanup_logs:
    name: Clear old log files
    runs-on: ubuntu-latest

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    permissions:
      contents: write

    steps:
      # Show trigger info
      - name: Show trigger info
        run: |
          echo "Triggered by: ${{ github.event_name }}"
          echo "UTC Time: $(date -u)"
          echo "IST Time: $(TZ=Asia/Kolkata date)"

      # CRITICAL: Run only on last day
      - name: Check last day of month
        run: |
          if [ "$(date -d tomorrow +%d)" != "01" ]; then
            echo "Not last day. Exiting..."
            exit 0
          fi

      # Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v5

      # Clean logs
      - name: Clean log files
        run: |
          if [ ! -d "Logs" ]; then
            echo "Logs folder not found."
            exit 0
          fi

          IST_TIME=$(TZ=Asia/Kolkata date "+%d-%m-%Y %I:%M:%S %p IST")

          find Logs -type f -name "*.log" | while read -r file; do
            {
              echo "This is removed by scheduler"
              echo "Cleanup Time: $IST_TIME"
            } > "$file"

            echo "Cleaned: $file"
          done

      # Commit only if changes exist
      - name: Commit changes
        run: |
          git config --global user.name "mairhythmhoon"
          git config --global user.email "rhythm.work.id@proton.me"

          git add Logs/

          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Monthly cleanup of log files"
          fi

      # Push changes
      - name: Push changes
        run: git push