name: Run App

on:
  schedule:
    - cron: "30 2 * * *"   # 8:00 AM IST
  workflow_dispatch: 	   # Allow manual run from GitHub UI

jobs:
  run:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt || echo "No requirements file"

      - name: Set timezone to IST
        run: |
          sudo timedatectl set-timezone Asia/Kolkata
          date   # (optional: shows current IST time in logs)

      - name: Set up Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Create Secure folder
        run: mkdir -p Secure

      - name: Create .env file
        run: echo "${{ secrets.ENV_FILE }}" > Secure/.env

      - name: Create credentials.json
        run: printf '%s' '${{ secrets.CREDENTIALS_JSON }}' > Secure/credentials.json

      - name: Run Python task
        run: python task01.py

      - name: Commit & Push changes
        run: |
          git add .
          git commit -m "Auto update: $(date)" || echo "No changes to commit"
          git push